# Generated by Django 5.0.3 on 2024-03-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('completa', models.BooleanField(default=False)),
            ],
        ),
    ]
